# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: release-please
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: cq-provider-sdk
          token: ${{ secrets.GH_CQ_BOT }}
          pull-request-title-pattern: "chore${scope}: Release${component} v${version}"
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
      - name: Parse semver string
        if: steps.release.outputs.release_created
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@966a26512c94239a00aa10b1b0c196906f7e1909
        with:
          input_string: ${{ steps.release.outputs.tag_name }}
      - name: Mark as pre-release
        if: steps.semver_parser.outputs.prerelease != ''
        uses: tubone24/update_release@202d50d2071038d7e940fa6fc07f7c39092b07c8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
        with:
          prerelease: true
